trajectory_encoder:
  target: cogkit.finetune.modules.trajectory_encoder.TrajectoryEncoder
  params:
    input_dim: 8
    d_model: 4096
    nhead: 8
    num_layers: 2
    target_traj_len: 226

trajectory_fuser:
  target: cogkit.finetune.modules.fuser.AdditionFuser
  params:
    empty: true

dataset:
  target_traj_length: 226


