compute_environment: LOCAL_MACHINE

gpu_ids: "0,1,2,3,4,5,6,7"
num_processes: 8  # should be the same as the number of GPUs

# gpu_ids: "0"
# num_processes: 1

debug: false

distributed_type: DEEPSPEED
deepspeed_config:
  # deepspeed_multinode_launcher: standard
  deepspeed_config_file: /gpfs/ebd/CogKit/quickstart/configs/zero/zero2_vela.yaml  # e.g. need use absolute path
  zero3_init_flag: false

downcast_bf16: 'no'
mixed_precision: bf16
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: z-chuang-yh-master-0
main_process_port: 23456
main_training_function: main
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false